### ISSUE TITLE
Change key bindings

### ISSUE THREAD

**Issue by localmemories** [artemsen/swayimg#1]
Nice image viewer!

is it possible to change key bindings? It seems like it uses an US keyboard layout by default.
Also I would like to change the keys for browsing through files because I don't have any page up or down keys on my notebook.

Thank you

**Comment by artemsen** [comment]
Sorry, there is no configurable key bindings. But it should work regardless of the keyboard layout, I was too lazy to implement even "repeat mode", so there is no any international support, just native linux key codes. 
However, I have added N and P key handlers for navigating between files, I hope this helps =)
