### ISSUE TITLE
More Zooming & Panning Shortcuts

### ISSUE THREAD

**Issue by SpaceshipOperations** [artemsen/swayimg#102]
Hello, first of all thank you for this nice app!

I would like to suggest a few really nice-to-have QoL shortcuts.

## Zooming Shortcuts

- Fit width: Fits image width to window width (even if the height is gonna be larger).
- Fit height: Fits image height to window height (even if the width is gonna be larger).
- Toggle zoom: Toggles between `zoom_fit` and `zoom_real`. More specifically:
    + If current zoom level is "fit", it switches to "real".
    + If current zoom level is "real", it switches to "fit".
    + If current zoom level is neither "fit" nor "real", it switches to "fit".

## Panning Shortcuts

It would be great to have the ability to configure multiple panning shortcuts with a different step size. For example it would be ideal for me to configure it like this:

```ini
[keys]
# Small steps
Up = step_up 1%
Down = step_down 1%
Left = step_left 1%
Right = step_right 1%

# Large steps
Shift+Up = step_up 30%
Shift+Down = step_down 30%
Shift+Left = step_left 30%
Shift+Right = step_right 30%
```

Likewise it would be great to be able to do the same for zooming:

```ini
[keys]
# Small step
equal = zoom_in 10%
minus = zoom_out 10%
# Large steps (with shift)
plus = zoom_in 25%
underscore = zoom_in 25%
```

Honestly if these are implemented, I would uninstall Gwenview forever lol.

**Comment by artemsen** [comment]
> Fit width: Fits image width to window width (even if the height is gonna be larger).
> Fit height: Fits image height to window height (even if the width is gonna be larger).

Looks like it is [zoom_fill](https://github.com/artemsen/swayimg/commit/d0a4a0ed46f01bd953536f3421f3baaa0ff27cf7) mode, `Z` key by default.

> Toggle zoom: Toggles between zoom_fit and zoom_real

For now, we have `zoom_optimal`, `zoom_fit`, `zoom_fill`, and `zoom_real` modes. You can bind them to any keys. Is it enough?

> It would be great to have the ability to configure multiple panning shortcuts with a different step size.
> Likewise it would be great to be able to do the same for zooming

I [did it](https://github.com/artemsen/swayimg/commit/4564487101c9b064a102caecfabe1e9b2f9777cb) 4 day ago =)
```
[keys]
Left = step_left 10
a = step_left 50
plus = zoom_in 10
b = zoom_in 20
```

But all these features are in the `master` branch and have not yet been released.
Also, key modifiers are not supported yet, so `Shift+Up` doesn't work.

**Comment by SpaceshipOperations** [comment]
Thank you for the quick reply.

>Looks like it is [zoom_fill](https://github.com/artemsen/swayimg/commit/d0a4a0ed46f01bd953536f3421f3baaa0ff27cf7) mode, Z key by default.

That one fits whichever is the smaller dimension. What I want is a shortcut that unconditionally fits the width of the image to the window, regardless of which dimension is bigger or smaller.

This feature is actually important to me, since there are various types of images that I would want to fit to the width of the screen in order to read their contents, such as scanned documents, comics, etc.

>For now, we have `zoom_optimal`, `zoom_fit`, `zoom_fill`, and `zoom_real` modes. You can bind them to any keys. Is it enough?

Well, this one is not really a big deal. The way I currently have it configured in Gwenview is using `F` as a "toggle zoom" key and `Shift-F` as a "fit width" key, which allows me to combine all of the zoom toggles that I frequently use in just one key. But of course, even if there had to be three bindings rather than two, I'd still be able to put them in nearly the same place.

I do think that it would be a nice-to-have QoL feature, since I can't be the only one who likes it.

>I [did it](https://github.com/artemsen/swayimg/commit/4564487101c9b064a102caecfabe1e9b2f9777cb) 4 day ago =)

Great to know!

**Comment by artemsen** [comment]
Fixed in https://github.com/artemsen/swayimg/pull/104
