### ISSUE TITLE
Window can no longer be larger than a single display

### ISSUE THREAD

**Issue by lbatalha** [artemsen/swayimg#110]
Previously I was using `swayimg` to display an image over all my displays (using `fullscreen enable global` in `sway` config). After a recent update (besides a few flags disappearing) this is no longer possible.

The main problem seems to be that I cannot even manually resize the `swayimg` window to be larger than one single display, so no combination of flags or sway settings will make this work again. Using fullscreen mode or not doesn't matter, manually setting the window size via `-g` does not work, `-p`, using the `sway` config or not also makes no difference.

This works correctly with `imv` as it did before, although `swayimg` is much faster

**Comment by artemsen** [comment]
Could you please describe the steps to reproduce the problem?
I have two displays and the command `swayimg -p 0,0 -g 4540,1440 image.jpg` shows the image on both displays.

**Comment by lbatalha** [comment]
The resize problem appears to be due to me having set `floating_maximum_size 3840 x 2160`, removing that makes it work correctly in windowed mode with `swayimg -p 0,0 -g 11520,4320 test.png`, sorry about that.

Previously I was using something like:
`for_window [app_id="swayimg-screenshot"] fullscreen enable global` while setting the window class to match, but that no longer works (it still does with `imv`), is there a way to make this old behavior work again? Tried with fullscreen `-f` mode but it does not seem to work.
For the time being I can override the `floating_maximum_size` specifically for the class which seems to work ok.

Thanks for the quick response and sorry for the confusion

**Comment by artemsen** [comment]
My be the problem is in the class name: `swayimg-screenshot` is not the app_id of `swayimg`.
By default `swayimg` uses a unique name (`swayimg_{timestamp}`), or constant `swayimg` if `sway` is not available.
You can set the name in the command line (`-a swayimg-screenshot`) or in the configuration (`[General] -> app_id=swayimg-screenshot`).

**Comment by lbatalha** [comment]
Yeah I am manually defining the the class name with `-a`

**Comment by artemsen** [comment]
Please describe the steps to reproduce the problem. I still don't understand what you want =)

>  is there a way to make this old behavior work again?

Please describe the expected behavior.

**Comment by lbatalha** [comment]
Previously I used `fullscreen enable global` instead of defining the origin etc.. in swayimg. Now that doesnt work, but defining the origin and `-g image` is ok.
Closing the issue as I can make it do what I want, just slightly differently, thank you for the help!
