### ISSUE TITLE
Browse the rest of the photos in the folder

### ISSUE THREAD

**Issue by char11** [artemsen/swayimg#112]
Is it possible to open a specific file in a folder (swayimg file.jpg) and browse the rest of the photos in that folder (pgdown/pgup)? I think it would be useful.

**Comment by artemsen** [comment]
Yes, it is possible via [configurable parameter](https://github.com/artemsen/swayimg/blob/be4d3b8afa368bf8e9d145ccb272b7364a73502d/extra/swayimgrc#L52).
Just create the file `/home/?/.config/swayimg/config` with the following text:
```
[list]
all = yes
```

**Comment by char11** [comment]
Great! Thanks!
