### ISSUE TITLE
PNG animation decoder regression

### ISSUE THREAD

**Issue by appashchenko** [artemsen/swayimg#113]
Приятно смотреть на чистый код, совсем не как у меня, однако взяли и потеряли часть логики.

1. После рефакторинга потеряли всю логику обработки dispose_op == PNG_DISPOSE_OP_PREVIOUS;
Смысл был в том, чтобы сохранить часть выходного буфера (canvas) по месту нового фрейма, вставить новый фрейм, обработать, а в конце итерации вернуть сохраненную часть выходного буфера обратно.
Можно вообще весь выходной буфер сохранить, если памяти дофига, но лучше фрагмент.
Новые функции pixmap позволяют вставить в dst по смещению, но не скопировать из src по смещению, поэтому на PR я не выдавил.
Снизу прикреплю анимацию, которая отображается некорректно.

2. Спецификация указывает: если в процессе декодирования произошла ошибка, а первый фрейм считан, декодер должен отбросить все фреймы, кроме первого.
Теперь же этого не происходит. Очистка всего, ldr_fmterror, иди качай нормальные картинки.

_Дешёвое и сердитое исправление первого пункта_
```
diff --git a/src/formats/png.c b/src/formats/png.c
index 70e0843..2ead216 100644
--- a/src/formats/png.c
+++ b/src/formats/png.c
@@ -107,6 +107,7 @@ static bool decode_multiple(struct image* ctx, png_struct* png, png_info* info)
         png_uint_32 frame_width = width;
         png_uint_32 frame_height = height;
         struct pixmap framebuf;
+        struct pixmap temp;
 
         if (!pixmap_create(&frame->pm, width, height)) {
             goto done;
@@ -142,6 +143,15 @@ static bool decode_multiple(struct image* ctx, png_struct* png, png_info* info)
             goto done;
         }
 
+        if (dispose_op == PNG_DISPOSE_OP_PREVIOUS) {
+            if (index > 0) {
+                pixmap_create(&temp, width, height);
+                pixmap_copy(&temp, 0, 0, &canvas, temp.width, temp.height);
+            } else {
+                dispose_op = PNG_DISPOSE_OP_BACKGROUND;
+            }
+        }
+
         switch (blend_op) {
             case PNG_BLEND_OP_SOURCE:
                 pixmap_copy(&canvas, x_offset, y_offset, &framebuf,
@@ -160,6 +170,11 @@ static bool decode_multiple(struct image* ctx, png_struct* png, png_info* info)
                         0);
         }
 
+        if (dispose_op == PNG_DISPOSE_OP_PREVIOUS) {
+            pixmap_copy(&canvas, 0, 0, &temp, temp.width, temp.height);
+            pixmap_free(&temp);
+        }
+
         if (delay_den == 0) {
             delay_den = 100;
         }
```
_Чудовище из-за PNG_DISPOSE_OP_PREVIOUS_
![swappy-20240201-112211](https://github.com/artemsen/swayimg/assets/58292846/5f1e0682-5e86-48c5-afba-5907e8363cd9)
_Исходная анимация_
![apng1](https://github.com/artemsen/swayimg/assets/58292846/4be44c43-bbee-4b9a-9403-0e9ef1af9f06)

**Comment by artemsen** [comment]
Спасибо!
