### ISSUE TITLE
Accept image list from file/stdin

### ISSUE THREAD

**Issue by SpaceshipOperations** [artemsen/swayimg#116]
Hello, I'd really love to have the ability to pass a list of images
to view via stdin or as a file.

This would be useful for e.g. viewing search results or some other
image list constructed in an arbitrary way, like this:

```bash
$ find ~/Pictures -type f -iname '*cat*.gif' -print0 \
    | swaymg --from-file0=-
```

Or this:

```bash
$ find ~/Pictures -type f -iname '*cat*.gif' -print0 > cat-gifs.txt
$ swayimg --from-file0=cat-gifs.txt
```

If you're open to the idea, I can help with a PR. :)

**Comment by artemsen** [comment]
You can link `find` and `swayimg` through `xargs`:
```
find ~/Pictures -type f -iname '*cat*.gif' -print0 | xargs -0 swayimg
```
We don't need to implement own `--from-file0` for that.

**Comment by SpaceshipOperations** [comment]
Ohh, you're right. For some reason I forgot I can just use `xargs -0` for this.

I'm closing the issue. Sorry about wasting your time.
