### ISSUE TITLE
Is it still able to display a picture on an empty sway workspace?

### ISSUE THREAD

**Issue by pralite** [artemsen/swayimg#117]
Hi, 
With a pre 2.1 version of swayimg, using sway on an archlinux derived distro,
I was able to call:
`waymsg workspace number $1 && swayimg --geometry 1720,60,210,150 --scale=fit --background=none /home/user/wmxchannelimgs/chan"$1".png &`
in a script and that would display the appropriate picture (workspace number), even if the workspace didn't have any windows (yet).

For 2.1, (on sway 1:1.8.1-)  I'v now come up with:
`swaymsg workspace number $1 && swayimg --config=general.antialiasing=no --config=general.position=1720,60
 --config=general.size=210,150 --config=general.scale=real --config=general.transparency=none --config=in
fo.mode=off  /home/user/wmxchannelimgs/chan"$1".png &`,
but that only works for workspaces that already have some window.

Is it still possible to display a picture on an empty workspace?

Additional info:
Quickly calling the script and rapidly switching workspaces leads to the side effect that the picture for empty workspace 1,
is displayed as a non-transparent one with it's own window in the next workspace that is being switched to (2).
Repeatedly doing this leads to the swayimg command not adhering to the commandline flags at all anymore and a 'Invalid IPC response' errormessage for every new swayimg execution.

However, the last misbehaviour could in theory be due to other code in the script handling the fading out and killing of the swayimg process or hiding of the kill-notification.

**Comment by artemsen** [comment]
Fixed.
Thank you for detailed bug report!
