### ISSUE TITLE
Option for disable key input (only draw image)

### ISSUE THREAD

**Issue by lievin-christopher** [artemsen/swayimg#122]
Hi,
I'm working at using swayimg in ranger for images preview.
But swayimg keep grab my input when I preview images in ranger. so I wonder if it's possible to implement a "no input" option ?

**Comment by artemsen** [comment]
Swayimg (like any other application) will grab input as long as its window has input focus.
You can configure Swayimg to ignore default key bindings by overriding them in the configuration file :
```
[keys]
Enter = none
```
However it doesn't solve your problem, ranger will not receive keyboard events until you set the input focus to its own window.
Swayimg itself cannot do this, this is the task of your compositor (Sway, Hyperland, ...).

**Comment by lievin-christopher** [comment]
Yes, I just find the issue.
It's linked to sway and this occur only on floating window (and maybe multi-monitor).
Thanks for your answer
