### ISSUE TITLE
Supporting of chinese character in the text info mode

### ISSUE THREAD

**Issue by alj212** [artemsen/swayimg#124]
I have a file that is name like this 

> Screenshot_測試.png

and when i open it in swayimg, the chinese character is not supported

![Screenshot_2024-04-12-12-42-55_swayimg](https://github.com/artemsen/swayimg/assets/87176344/724f0e6b-8da9-4937-8470-8abdd328babf)

I have installed noto-fonts-cjk and i dont face any issue on firefox so I think it might be an issue with swayimg?

**Comment by artemsen** [comment]
By default, swayimg uses the `monospace` font to render text.
You can try to change this setting in the [config file](https://github.com/artemsen/swayimg/blob/31b4c6253d7bfbd3e8f14d59b91e69f24f9b61f6/extra/swayimgrc#L61).

**Comment by alj212** [comment]
I have tried these configurations but none of it works.

> 
> name = noto-cjk
> name = sans-serif
> name = serif

**Comment by artemsen** [comment]
You should specify the correct font name.
For instance, I have installed Noto from [here](https://github.com/notofonts/noto-cjk/blob/main/Serif/OTF/SimplifiedChinese/NotoSerifCJKsc-Regular.otf) and set its name `Noto Serif CJK SC`, so here is the result:
![image](https://github.com/artemsen/swayimg/assets/1169976/95aad79a-dd79-4b54-9e96-c7d9f9b268d5)

You can use `fc-list` to get font name:
```
$ fc-list | grep -i noto
/home/art/.config/fontconfig/NotoSerifCJKsc-Regular.otf: Noto Serif CJK SC:style=Regular
```

**Comment by alj212** [comment]
Yes, it works. 
Thank you!
