### ISSUE TITLE
pass through touch/mouse events

### ISSUE THREAD

**Issue by magdesign** [artemsen/swayimg#125]
is there an option to pass through all touch/mouse events?
so swayimg could for example display a watermark.png with transparency over the full workspace while the user can still interact with touch or mouse to the underlaying workspace.

**Comment by artemsen** [comment]
Unlike X11, Wayland prohibits direct interaction between windows of different processes.
It is possible to pass the events, but it will require some hacks, such as root rights to manipulating with /dev/uinput. But it is out of an image viewer functionality.

**Comment by magdesign** [comment]
ok. thanks for your fast replay....
 then i need to find another way to make 'fake' gamma adjustments with an overlaying png 😅
