### ISSUE TITLE
still keymaps

### ISSUE THREAD

**Issue by JeromeSchmied** [artemsen/swayimg#127]
Thank you for dealing with #126 so fast, I cloned the repo and built `swayimg` but I'm afraid the issue is still not quite resolved.

The problem is, that keymaps I add with Shift eg `Shift-j` don't do anything, whereas `Shift-m` which is a default for mirroring works completely fine.

Also `bracketleft`(`AltGr-f`) and `bracketright`(`AltGr-g`) work correctly, but still `question`(`Shift-3`) doesn't do anything.

**Comment by artemsen** [comment]
I have just checked `Shift+j` (`+`, not `-`), it works fine. I can't reproduce the error =(
`Shift+3` doesn't work, but as workaround you can set `Shift+#` (`#` is `3` on your keyboard, right?).

**Comment by JeromeSchmied** [comment]
Yeah, sorry, I have `Shift+j` in my config, I've just accidentally written `Shift-j` in the comment.

This is how my keyboard layout looks like:
![my kbd layout looks like this](https://sfkornyek.szabadsagharcos.org/hunkeyb.gif "this is how my keyboard layout looks like")

so if I type `Shift+3` I get `?`

**Comment by artemsen** [comment]
>so if I type Shift+3 I get ?

Please, provide output from `xkbcli interactive-wayland` for this combination.

**Comment by JeromeSchmied** [comment]
sorry, wrong character, I corrected it in my comment, but here is my `xkbcli interactive-wayland` output:
```shell
$ xkbcli interactive-wayland

seat0: keycode [ RTSH ] keysyms [ Shift_R                     ] unicode [   ] layout [ Hungarian (0) ] level [ 0 ] mods [ ] leds [ ]
seat0: keycode [ AE03 ] keysyms [ plus                        ] unicode [ + ] layout [ Hungarian (0) ] level [ 1 ] mods [ -Shift ] leds [ ]
seat0: keycode [ LFSH ] keysyms [ Shift_L                     ] unicode [   ] layout [ Hungarian (0) ] level [ 0 ] mods [ ] leds [ ]
seat0: keycode [ AE03 ] keysyms [ plus                        ] unicode [ + ] layout [ Hungarian (0) ] level [ 1 ] mods [ -Shift ] leds [ ]
seat0: keycode [ LFSH ] keysyms [ Shift_L                     ] unicode [   ] layout [ Hungarian (0) ] level [ 0 ] mods [ ] leds [ ]
seat0: keycode [ AB08 ] keysyms [ question                    ] unicode [ ? ] layout [ Hungarian (0) ] level [ 1 ] mods [ -Shift ] leds [ ]
seat0: keycode [ RTSH ] keysyms [ Shift_R                     ] unicode [   ] layout [ Hungarian (0) ] level [ 0 ] mods [ ] leds [ ]
seat0: keycode [ AB08 ] keysyms [ question                    ] unicode [ ? ] layout [ Hungarian (0) ] level [ 1 ] mods [ -Shift ] leds [ ]
seat0: keycode [ RALT ] keysyms [ ISO_Level3_Shift            ] unicode [   ] layout [ Hungarian (0) ] level [ 0 ] mods [ ] leds [ ]
seat0: keycode [ AC04 ] keysyms [ bracketleft                 ] unicode [ [ ] layout [ Hungarian (0) ] level [ 2 ] mods [ -Mod5 ] leds [ ]
seat0: keycode [ RALT ] keysyms [ ISO_Level3_Shift            ] unicode [   ] layout [ Hungarian (0) ] level [ 0 ] mods [ ] leds [ ]
seat0: keycode [ AC05 ] keysyms [ bracketright                ] unicode [ ] ] layout [ Hungarian (0) ] level [ 2 ] mods [ -Mod5 ] leds [ ]
```

**Comment by artemsen** [comment]
I am not sure which one is for the `Shift+3` combination, but I suspect it is `question` =)
Try `Shift+question`.
Anyway, swayimg now prints all unhandled/unknown keys. Could you build the latest master and try to find the combination?

**Comment by JeromeSchmied** [comment]
wow, great I'll try it soon

**Comment by JeromeSchmied** [comment]
now this one's a useful feature, thank you very much for the improvements you made!

turns out `Shift+j = step_down 10` was working the whole time, only I thought it wasn't, as I didn't zoom enough into the picture, sorry ;)

and also, `Shift+question` works just as expected, although it's still a bit weird.
