### ISSUE TITLE
swayimg segfaults when decoding /dev/zero or /dev/null

### ISSUE THREAD

**Issue by vursc** [artemsen/swayimg#129]
Steps to reproduce:
```
$ swayimg /dev/zero
Segmentation fault (core dumped)

$ swayimg /dev/null
Segmentation fault (core dumped)
```

I inspected the format-independent code for loading the image and found nothing suspicious, and suspect that it is some `detect_<format>`'s fault.

GDB `list` pointed to some nonexistent header file `/usr/src/debug/gcc/gcc/libgcc/emutls.c`. Not sure what this means.

(Zstd-compressed) core dumps: [core_dumps.zip](https://github.com/artemsen/swayimg/files/15058555/core_dumps.zip)

**Comment by artemsen** [comment]
Just curious, why open `/dev/null` in swayimg?

**Comment by vursc** [comment]
Not really `/dev/null`... I accidentally opened an empty file (created by a faulty image format conversion). Thanks for the quick fix!

**Comment by vursc** [comment]
Just realized that `/dev/zero` has size zero... Should have noticed that earlier :P
