### ISSUE TITLE
Feature request: no window resize option

### ISSUE THREAD

**Issue by exoess** [artemsen/swayimg#130]
an option to make the window the exact same size as the image and make it so you can't resize past that size

**Comment by artemsen** [comment]
You can set the initial window size based on the image size via a [configuration option](https://github.com/artemsen/swayimg/blob/5be9926e48b140cabccd9fa14ebc0d2fb4820a33/extra/swayimgrc#L34).
After launch, Swayimg itself does not change the window size, only user/compositor can do it.

**Comment by exoess** [comment]
i've seen wayland windows change size independent of compositor, and the size won't be static, it can still be resized

**Comment by artemsen** [comment]
Sorry, I don't get your proposal.
If you don't want resize the window - don't do it =)

**Comment by exoess** [comment]
sorry, i'm probably not explaining this in the best way, i could just make a video of the patch i made

**Comment by artemsen** [comment]
I am closing this bug because there is not enough information to implement the feature.
If it's still relevant, please feel free to reopen it and describe step-by-step what you need.

**Comment by nojvspine** [comment]
Does this still work? Or we need to implement it through lua?

**Comment by artemsen** [comment]
> Does this still work? Or we need to implement it through lua?

What is "this"? I still have no idea what this issue is :/

**Comment by nojvspine** [comment]
Sorry, I was talking about setting window size equal to image size
Also I have a problem with displaying images on a scaled display, but maybe this is better to discuss in another issue

**Comment by artemsen** [comment]
> setting window size equal to image size

May be [this](https://github.com/artemsen/swayimg/issues/503#issuecomment-4638571984) helps.
