### ISSUE TITLE
Add config option to only apply antialiasing to scaled images

### ISSUE THREAD

**Issue by charbelnicolas** [artemsen/swayimg#131]
Like the title says, it would be nice if we could specify in the config to only apply antialiasing to scaled images. As it is right now even non-scaled images get antialiased and they look blurry.

Aliased:

![ss_2024_04_29_18_34_57](https://github.com/artemsen/swayimg/assets/14960414/9702666c-1e29-4336-8fb5-c32ba1724fc6)

Antialiased:

![ss_2024_04_29_18_35_28](https://github.com/artemsen/swayimg/assets/14960414/b77246ed-95f6-43c5-b09b-61813f45b312)

I might be wrong but I think this is how feh does it, it only applies antialiasing when needed.

**Comment by artemsen** [comment]
I don't think we need a standalone option for this.
Antialiasing will now be disabled for a scale of 100%.

**Comment by charbelnicolas** [comment]
Sweet! That was fast, thank you!
