### ISSUE TITLE
Feature request: Remove an image from the list

### ISSUE THREAD

**Issue by rempas** [artemsen/swayimg#132]
First, I would like to thank you for that amazing application! I was searching for an alternative for feh (as Artix does not support Xwayland, so I can't use it without having to compile things from source) and I found swayimg and, I can say that it is amazing!

One feature I would like to request is the ability to remove an image from the viewing list. Not get confused with removing the image FROM THE SYSTEM (which I do with `Shift+d = exec rm "%"`). I am requesting a way to remove the image from the current image list that is viewed but not remove it from the system.

**Comment by artemsen** [comment]
Done!
The default key is `c`, you can use the `skip_file` action to set own keybinding.

**Comment by rempas** [comment]
> Done! The default key is `c`, you can use the `skip_file` action to set own keybinding.

Damn, that was so cool! Thank you so much and have an amazing day! :heart:

**Comment by rempas** [comment]
@artemsen I just tried to use it before. Hasn't it been added in version 2.2?

**Comment by artemsen** [comment]
No, it will be included in version 2.3.
To use this feature now, you need to build the program from source.

**Comment by rempas** [comment]
> No, it will be included in version 2.3. To use this feature now, you need to build the program from source.

Oh, ok! I thought of asking in case there was a bug or something, so I thought to let you know.

Thank you for the reply! Have a beautiful day!
