### ISSUE TITLE
reads all images in directory when passed a single file

### ISSUE THREAD

**Issue by jonassmedegaard** [artemsen/swayimg#133]
In a directory containing two PNG images I run `swayimg PCDM_Multi_Page_Text-circles.png` and expect only that image to load, but both images load.
If I pass two paths, for a single image in two different directories, then all images of both directories get shown, where I would expect only the two explicitly stated files to load.

Tested with swayimg 2.2 packaged for Debian.

**Comment by artemsen** [comment]
Works as designed. By default, swayimg reads all images from the directory.
You can change this behavior in the [config](https://github.com/artemsen/swayimg/blob/0689f5e82a6bad13497ddd6d598b1a2b53ac1390/extra/swayimgrc#L54) file.

**Comment by artemsen** [comment]
Actually, it doesn't "load all files" (but preloads the next one).
Swayimg creates the file list with all files and set the starting entry to the specified file.
If you don't specify any file, it creates a list of all files in the current current directory and tries to open the first entry.

Sorry, English is not my native language, so there may be some misunderstanding in the documentation.
Please, feel free to create a pull request with the fix =)

**Comment by artemsen** [comment]
> This application never only loads what you pass it as command-line options. Instead it always (pre)loads all image files it can find, taking command-line options only as a) files to place in front of the viewing queue, and b) places to look for images in.
Is that correctly understood?

No, it is not correct.
1. By default (`all = yes`), the application creates the image list with all files in the same directory, but loads only one specified in the command line and preloads next one image.
2.  If you set `all` to `no`, then swayimg will load only specified image. But if you don't specify any file - the image list will contain all files in the current directory and swayimg loads the first available image and preloads the next one.

> I base this interpretation also on adding the following at /etc/xdg/swayimg/config

It is a system-wide config. I would recommend `$HOME/.config/swayimg/config`.

> [general]
all = no

Wrong section. You should use `list` instead of `general`. See [example](https://github.com/artemsen/swayimg/blob/0689f5e82a6bad13497ddd6d598b1a2b53ac1390/extra/swayimgrc#L54).

**Comment by jonassmedegaard** [comment]
> Wrong section. You should use list instead of general. See [example](https://github.com/artemsen/swayimg/blob/0689f5e82a6bad13497ddd6d598b1a2b53ac1390/extra/swayimgrc#L54).

Ah, my mistake. With that correction (which was totally my mistake not reading manual page carefully enough) the tool behaves how I would expect it to.

I still find it weird that `all = yes` is the default behaviour, but sounds like you are not open to changing that, so no point in offering patches, and I'll simply close this as a non-bug.

**Comment by artemsen** [comment]
> I still find it weird that all = yes is the default behaviour, but sounds like you are not open to changing that

Some people [want](https://github.com/artemsen/swayimg/issues/112) to open an image and see its neighbors. It's convenient for me too =)

**Comment by jonassmedegaard** [comment]
I understand now that (by default) swayimg treats FILE argument passed as command-line argument not (as is the default in many many other similar tools, and many of them the only possible behaviour) to only display FILE, but instead to display all files in same directory as FILE, with FILE being displayed first.

I see a point in it being possible to hint at prioritization rather than selection, but find it quite odd to have that behavior be the *default* behavior.

What I would find a more sensible way to get same behavior was to call it as `swayimg FILE *`.

**Comment by jonassmedegaard** [comment]
...or more concretely, to clarify my imagined behavior for a case of FILE being in a subdir:
```shell
swayimg subdir/myimg.png subdir/*
```

...but sure, that is more typing than the (to me weird) current behavior.
I just wish it wasn't the default, because I imagine that my expectations for an image viewer is more common than yours - but obviously you have absolutely no need to care for anyone else than yourself :-)
