### ISSUE TITLE
PR for new features?

### ISSUE THREAD

**Issue by nicolasbrailo** [artemsen/swayimg#135]
Been hacking a bit for a project on my Swayimg fork (https://github.com/nicolasbrailo/swayimg) and ended up with a few features that may be useful upstream. The code isn't quite PR-worthy (nor stable) yet, but if there's interest I can clean it up and send a few PRs.

Possibly non exhaustive list of things I added:

* Files are fetched from a configurable URL
* The info blocks have a solid background
* Info blocks timeout (eg in a slideshow where frames are shown for 10 seconds, exif can be shown for 5 seconds, then hidden)
* Touch screen support

Is there interest for any of these features as PRs?

**Comment by artemsen** [comment]
>  Files are fetched from a configurable URL

Sorry, but definitely no. Swayimg is not a network application.
You can mount a remote directory via WebDAV, SSHFS or any other protocol and use the network functionality separately from the image viewing application.
Besides the dependence on the curl, there is another problem - setting up the connection. How, for example, can you disable https certificate checking or prevent redirects from being processed? And what about passwords? Storing more than 250 curl options in the swayimg config is a bad idea.

> The info blocks have a solid background
> Info blocks timeout (eg in a slideshow where frames are shown for 10 seconds, exif can be shown for 5 seconds, then hidden)
> Touch screen support

This may be interesting, but please create separate PRs for each feature.
I don't have a touch screen, so you will have to describe what exactly this support means.

P.S. I'm away from my laptop until the end of June, so you don't have to rush =)
