### ISSUE TITLE
JPEG XL support

### ISSUE THREAD

**Issue by Seirdy** [artemsen/swayimg#14]
JPEG XL support could be provided by libjxl. This is actually a dependency of libavif on many distros (libavif depends on libaom, which depends on libjxl for butteraugli scoring), so the addition of an one more dependency shouldn't be too problematic.

Support for this image format will be rolling out to Firefox and Chromium in the coming months.

**Comment by Seirdy** [comment]
Also worth noting that JPEG XL does support optional animation like WebP, so #9 might be relevant.

**Comment by artemsen** [comment]
I have libavif v0.9.3 and there is no any implicit dependencies to libjxl in my system.
Anyway, I've added XL support to the master branch, very basic support (no multithreads, no ICC).
