### ISSUE TITLE
swayimg trying to open non-image files too?

### ISSUE THREAD

**Issue by user451421541757324** [artemsen/swayimg#144]
I use swayimg with `[list] all = yes` option, however I believe it tries to open non-image files as well.

This is an error message I get from vifm:

![21062024130855](https://github.com/artemsen/swayimg/assets/109753483/eb2f69ce-04e5-45d9-83fc-8c57d95b0023)

`chrome.desktop` and `code.desktop` are two files that are in the same directory as the image that I opened with swayimg.

**Comment by artemsen** [comment]
If this option is enabled,
Swayimg tries to preload  images from the same dir. The application doesn't
rely on the file extension and uses signatures to detect image type.

Works as designed ;)
