### ISSUE TITLE
Container sizing and placement do not function normally when swayimg is launched from a floating container

### ISSUE THREAD

**Issue by hariganti** [artemsen/swayimg#147]
# Summary #
`swayimg` appears to size its floating container and position it so it's overlaid on the parent container; however, when executing `swayimg` from a floating container, the rules don't seem to work correctly, and the image is either tiled (if other containers are present) or maximized to the workspace

# Preconditions #
`swayimg` is executed from a floating container with a terminal emulator. No window rules are present for `swayimg` in the user Sway config

# Expected Behavior #
The image displayed by `swayimg` should be sized according to the parent container and positioned to overlay it

# Actual Behavior #
If there are other containers in the workspace, the image is tiled. if there are no other containers (other than the floating parent), it is displayed as maximized within the workspace (technically still tiled, so not really distinct). This is 100% reproducible on my system

# Config File #
```
[info]
# mode=off
full.topleft=none
full.bottomright=name,format,filesize,imagesize
```

# System Details #

- Ubuntu 24.04 LTS
- Sway 1.9
- WezTerm 20240203-110809-5046fc22
- Fish 3.7.1

**Comment by artemsen** [comment]
The issue was fixed in commit [6ab8d2c](https://github.com/artemsen/swayimg/commit/6ab8d2c7999aff99eebb0c5d1e01e3d4dbe86100), but this fix is ​​included in swayimg version 2.2.
I assume you are using swayimg 2.1 from Ubuntu 24.04, so you will have to build the viewer yourself to get a working version.

**Comment by hariganti** [comment]
Well that was an easy resolution. Sorry if I missed a prior issue that led to that fix, but I'll take a look at building the newest version. As you said, I am on 2.1 since I originally `apt` installed it.

Thank you!

**Comment by hariganti** [comment]
Seems to work well for me, thank you!

**Comment by artemsen** [comment]
You are welcome! =)
