### ISSUE TITLE
hidpi issue?

### ISSUE THREAD

**Issue by pg83** [artemsen/swayimg#15]
I believe that swayimg incorrectly display files in hidpi wayland mode. I can see that every displayed image pixel consists of 2x2 display pixels in reality.

**Comment by artemsen** [comment]
Swayimg doesn't have any dpi-specific handlers and [draws](https://github.com/artemsen/swayimg/blob/d5b3aa2dd4c8e718253247aad1aaff33ce346ea2/src/canvas.c#L43) an image only applying the current scale/flip/rotate factors.
Could you provide an example image and a screenshot of the incorrect display?

**Comment by pg83** [comment]
I'll try to do it later, but you can reproduce it by adding "scale 2" parameter for your output device in sway/config. If I set it to 1, I can see perfect pixel-wise image, but if I set it to 2, I see double-pixels.

I think that image viewer should set scale parameter of wayland surface to 1.

**Comment by artemsen** [comment]
I tried to deep into the sway output config, it seems the scale factor is set for the entire output device.
I mean, it is not a window or surface property, the scale is always set for the particular display.
To be frankly, I didn't find any methods to ignore output scale in surface, if you have any ideas - let me know.

**Comment by progandy** [comment]
> To be frankly, I didn't find any methods to ignore output scale in surface, if you have any ideas - let me know.

You should read the output scale, then create a surface with the desired size (logical size * scale) and tell the compositor that the surface is using the same scale as the output.

**Comment by pg83** [comment]
Works like a charm, thank you!
