### ISSUE TITLE
Pixelated font after 2.3 update

### ISSUE THREAD

**Issue by izmyname** [artemsen/swayimg#150]
Since the update 2.3, my font looks like this. No changes in the config were made.

```
 ################################################################################
 # Font configuration
################################################################################
 [font]
# Font name
 name = monospace
# Font size (in pt)
 size = 12
 # Font color
 color = #cccccc
 # Drop shadow (none/RGB, e.g. #112233)
shadow = #000000
```

![slurp_screenshot](https://github.com/artemsen/swayimg/assets/135810812/3baf349c-d6b5-4fc0-9c7f-7650ac73d34e)

**Comment by g-rden** [comment]
For the time being you can avoid this by adding alpha channel with '0x00' value to the colors. 
`color = #cccccc00`
`shadow = #00000000`

**Comment by izmyname** [comment]
My font looks normal now, thank you.
