### ISSUE TITLE
Meson setup fails on Alpine Linux

### ISSUE THREAD

**Issue by g-rden** [artemsen/swayimg#155]
`meson.build:57:9: ERROR: C shared or static library 'gif' not found
`

Replacing `gif = cc.find_library('gif', dirs: wlcln.get_variable(pkgconfig: 'libdir'))` with the old `gif = cc.find_library('gif', required: get_option('gif'))` makes meson setup able to run successfully with the message:
`Library gif found: NO`

Btw giflib is installed
```
$ apk list giflib
giflib-5.2.2-r0 x86_64 {giflib} (MIT) [installed]
```

**Comment by artemsen** [comment]
Yeah, it is regression after https://github.com/artemsen/swayimg/commit/6a6678a6bffb73b8adb5863e7a2ba4ccb79eda05

**Comment by artemsen** [comment]
> Btw giflib is installed

You need `giflib-dev`, it includes header files.

**Comment by g-rden** [comment]
Now it works, thanks!

> You need giflib-dev, it includes header files.

Yes, i forgor
