### ISSUE TITLE
Text cut off and glyphs don't display

### ISSUE THREAD

**Issue by g-rden** [artemsen/swayimg#156]
With smaller font size <= 12pt text is cropped.
Some glyphs don't display, no matter the font size, but happens more if the size is smaller.

fira 9pt:
![crop](https://github.com/user-attachments/assets/e37dad59-1574-4556-9abb-fd05898aa2ae)
it should be 
```
File name    check.png
Image format PNG 32bit
File size    0.21 KiB
Image size   100x100
```

Skipping glyphs is caused by this being true `x + bmp->width >= surface->width`

I tried fixing it, but I can't. Some font, size or on a different OS (most likely the difference in specific font provided) is always messed up in some way.

**Comment by artemsen** [comment]
I'm tired of font errors...
Perhaps it's time to return to pango.
