### ISSUE TITLE
Crash open gallery mode

### ISSUE THREAD

**Issue by mantarimay** [artemsen/swayimg#162]
Distro: Tumbleweed
Version: [2.5](https://build.opensuse.org/package/show/X11:Wayland/swayimg)

try open `swayimg -g` but result app crashed

```
#0  0x000055a0bc1b3dbc in app_init
    (num=<optimized out>, sources=<optimized out>)
    at ../src/application.c:288
        pm = Python Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0x20
#1  main
    (argc=<optimized out>, argv=<optimized out>)
    at ../src/main.c:176
        rc = false
        argn = <optimized out>
```

**Comment by artemsen** [comment]
Sorry, I always forget that besides Sway there are other WMs =)
I'll fix it ASAP, but as workaround you can open `swayimg` as usual in viewer mode and then switch to the gallery by the `Enter` key.
