### ISSUE TITLE
Gallery mode - use zoom +/- keys to move focus to an image above/below the current one.

### ISSUE THREAD

**Issue by izmyname** [artemsen/swayimg#164]
Currently, it's not possible to move focus (selection) one string above or below, when in gallery mode. My suggestion, as the title says, is to add this functionality to zoom +/- keys, if possible.

**Comment by artemsen** [comment]
It is possible with up/down keys by default. You can [bind](https://github.com/artemsen/swayimg/blob/fbd60d5c8c118e7fecbcc604680e5e2d1f2afe44/extra/swayimgrc#L136) other keys to `step_up`/`step_down`.
Zoom keys will be used for their intended purpose in the future (change thumbnail size).

**Comment by izmyname** [comment]
Yep, `step_up/step_down` keys work, although I don't find it very comfortable to use, since `up/down` keys are more often used to zoom an image, and their usage to move the focus above/below in the gallery mode would look more natural, in addition to left/right keys as move the focus to the previous/next image, but this is a mater of a personal preference and configuration, I guess. 

Thanks for the answer, closing the issue.

**Comment by artemsen** [comment]
> Perhaps, it's possible to add some sort of 'swap functionality of zoom and step keys in gallery mode' config option?

Currently, no. I had an idea to separate the key configuration for viewing and gallery, but it breaks the configuration file format and makes it incompatible with the previous version. Maybe in future releases.
