### ISSUE TITLE
memory leak when resizing windows

### ISSUE THREAD

**Issue by qaako** [artemsen/swayimg#165]
Hi, i'm not the best at troubleshooting these things. but I will debug however I can if you provide instructions.

This app uses up to 4.9GB of RSS in less than 30 seconds with one image open.
Sometimes it's as little as 800MB, most of the time it's more than 1GB. All in less than 30sec here, I have never had it open longer than 60 seconds due to this issue. I've only discovered the existence of this less than 24 hours ago, and so far I've been unable to use it.

Using Arch Linux and this occurred with newest distro package, v2.5, and I also tried downgrading to v2.2 from the Arch Linux Archive and it didn't help.
Problem occurs on Sway and KDE Wayland.
I haven't tried building myself from source.

I've only tested on JPEG (less than 1080p) and PNG (24x24 icon from /usr/share/icons or /usr/share/pixmaps). Problem occurs on all images.

Using intel igpu with distro provided linux-zen kernel. The only weird settings I can think of that might differentiate me from the norm is I do have HuC/GuC firmware enabled for i915. But I've never had problems from any other app, and been using this setting for 2 years.

I really want this to work, because no wayland image viewer comes close to feh when it comes to RSS/memory footprint and image format support. people recommend imv but it's much more memory hungry than feh is.
Hope I didn't break any rules by mentioning those two software, im new to posting on github.

**Comment by artemsen** [comment]
Hmm... This is indeed a memory leak, I reproduced it.
I use resize so rarely that I didn't even notice this bug before =)
