### ISSUE TITLE
Swayimg crashes in gallery mode

### ISSUE THREAD

**Issue by zootedb0t** [artemsen/swayimg#166]
Distro: Arch Linux
DE: Hyprland
swayimg version 2.5.
https://github.com/artemsen/swayimg
Supported formats: bmp, pnm, tga, jpeg, png, gif, webp, svg, heif, avif, avifs, jxl, exr, tiff.

When i try to launch swayimg in gallery mode, it crashes with a
`Segmentation fault (core dumped)`.
However, i can launch swayimg normally and then enter gallery mode by pressing `Enter` key.

**Comment by artemsen** [comment]
Duplicate #162
