### ISSUE TITLE
Can't open image over 32767 pixels long in any direction

### ISSUE THREAD

**Issue by bgkillas** [artemsen/swayimg#17]
the output is just 
`Unable to create surface
`
`Unsupported file format: canvas.png
`

**Comment by artemsen** [comment]
Swayimg uses [Cairo](https://www.cairographics.org) to draw, flip, and rotate images.
Unfortunately, the Cairo library has hard-coded limits on the size of image surfaces, the maximum size in width or height cannot be more than [32767 pixels](https://github.com/freedesktop/cairo/blob/cd21fa08144fe22d0b4c28a77f654b4e6fda11ef/src/cairo-image-surface.c#L62).
Sorry, but I don't think support for such large images will be implemented in the near future.
