### ISSUE TITLE
Nix build broken with giflib workaround

### ISSUE THREAD

**Issue by diniamo** [artemsen/swayimg#179]
6a6678a6bffb73b8adb5863e7a2ba4ccb79eda05 broke the Nix build, of course, a revert patch is possible, but not preferred. Any idea why?

```
meson.build:57:9: ERROR: C shared or static library 'gif' not found
```

**Comment by artemsen** [comment]
Sorry, I am rather a Linux-guy than FreeBSD one =)
This was done by [advice](https://github.com/artemsen/swayimg/commit/99a66a4bfca043538a19db502c6b82733584df39#r144177569) from FreeBSD maintainer.
I tried to revert this fix and [build fails](https://github.com/artemsen/swayimg/actions/runs/10429668495/job/28887362184#step:3:1898), so it works at least for FreeeBSD 14.1.

**Comment by diniamo** [comment]
Would it be possible to check with pkgconfig first, and use the workaround as a fallback?

**Comment by artemsen** [comment]
The problem is that giflib doesn't support pkg-config.

**Comment by diniamo** [comment]
How? It used to work before the commit, which only fixed the FreeBSD build.

**Comment by artemsen** [comment]
Perhaps it depends on giflib path. Or may be it because of [this](https://github.com/mesonbuild/meson/issues/4468) bug. 
GitHub CI and freshports.org [say](https://www.freshports.org/x11/swayimg) this fix is ​​fine.
Sorry, I don't know how to make it work in FreeBSD without this patch. Do you have any ideas?

**Comment by diniamo** [comment]
Nothing other than what I've already suggested: using the workaround as a fallback.

**Comment by diniamo** [comment]
That seems to have done it, thanks! Would it be possible to make a release with this soon? The nixpkgs version is pretty outdated.

**Comment by artemsen** [comment]
I need to fix a couple of bugs. We'll be released by the end of summer.
