### ISSUE TITLE
Feature Request : allow navigation of images in a folder and define sort type

### ISSUE THREAD

**Issue by Iss-in** [artemsen/swayimg#18]
Will it be possible to add functionality to open a random image in a folder and then can navigate to other images in the directory via arrow keys.

I would also love to be able to navigate through images in a sorted  ( last modified or a-z ) order 

hope you will consider adding these features  :)

**Comment by roland-rollo** [comment]
Hmm. Not for me. If I try from console or from file manager it's only allow me to see that one image, and arrows or N/P didn't work to see other pictures.

**Comment by Tajnymag** [comment]
Did you pass a folder name or a glob? I haven't tried passing just a folder name.

**Comment by roland-rollo** [comment]
I'm not sure what passing glob mean, so it's little embarassing. I tried something like this
```
swayimg Download/picture1.jpg
```
But this allow me only to see this one image, even if there are others in folder Download.
If I try
```
swayimg Download/*
```
I can see with N/P everyone pictures in this folder.

**Comment by Tajnymag** [comment]
Yes, I meant `Downloads/*`

**Comment by Iss-in** [comment]
yeah, passing folder glob works, but that's not what I want.  

I should be able to open a image via mouse click from file manager and then should be able to navigate left or right to other images in the way the folder is sorted in the file manager

**Comment by artemsen** [comment]
Sorry, but Swayimg doesn't have integration with external file managers.
This is a simple tool designed for viewing images only.
If you need anything else, I would suggest using photo management software, something like digiKam.

The good news is that you can pass filenames to Swayimg in any order, for example:
```
# view all jpg in current dir sorted by size
swayimg $(ls -S *.jpg)

# view in random order
swayimg $(ls *.jpg | shuf)
```

**Comment by Iss-in** [comment]
so it is just not possible to start with an index in from the order. say I have image1, image2, image3 in that order, and I want swayimg to start from image2 and then cycle in clockwise order ?
