### ISSUE TITLE
Feature: deleting images

### ISSUE THREAD

**Issue by o0nd7ots** [artemsen/swayimg#181]
I would like to use swayimg as my image viewer but it does not allow for deleting images.

Is this possible to implement?

**Comment by artemsen** [comment]
Just press [Shift+Delete](https://github.com/artemsen/swayimg/blob/c292badd52ae8e99278a8d11f92f9f90f4e88084/extra/swayimgrc#L168).

**Comment by o0nd7ots** [comment]
that bind does not seem to work and I cannot custom ones:
```
$ cat config 
[keys.viewer]
F2 = help
```
and when running it
```
$swayimg 
Invalid section "keys.viewer"
Invalid configuration in /home/user/.config/swayimg/config:2
```

**Comment by artemsen** [comment]
It seems you have old version of swayimg.
You can find settings example for your version in `/usr/share/swayimg/swayimgrc`.
But I would recommend to update =)

**Comment by o0nd7ots** [comment]
You were right, updating helped. Thanks!
