### ISSUE TITLE
[Feature request] Reversing the sort order

### ISSUE THREAD

**Issue by alj212** [artemsen/swayimg#184]
Is it possible to implement the functionality to reverse the order of the images

`swayimg -r ~/Pictures -o alphareverse`

Much like how _feh_ implements the functionality
> Reverse the sort order. Use this to invert the order of the filelist.

**Comment by artemsen** [comment]
Done, just use `--order=reverse` or set default order in the [config file](https://github.com/artemsen/swayimg/blob/7f8929269485ed67193e2ca356cc13b91796f638/extra/swayimgrc#L83).
