### ISSUE TITLE
swayimg: error while loading shared libraries: libjxl.so.0.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by charbelnicolas** [artemsen/swayimg#187]
Hello Artem, libjxl just got upgraded to version 0.11 so swayimg isn't working anymore, it's asking for version 0.10.

`swayimg: error while loading shared libraries: libjxl.so.0.10: cannot open shared object file: No such file or directory`

**Comment by artemsen** [comment]
libjxl is the worst image image library in the world =) It has an ugly API and a terrible approach to versioning. Any minor change breaks all applications that depend on this library.
You have to rebuild swayimg from source, this fixes the issue.

**Comment by appashchenko** [comment]
no it is not. but if you guys do not use your distro package manager and do build programs yourself so you must watch for dependencies. just rebuild swayimg from source.

**Comment by charbelnicolas** [comment]
Ohhh, sorry, that's right, thank you. I'll rebuild.
