### ISSUE TITLE
Add support for QOI format

### ISSUE THREAD

**Issue by sepisoad** [artemsen/swayimg#194]
Hello dear @artemsen 

I am working on a tool which requires me to deal with [QOI](https://qoiformat.org/) images, I went ahead and modified swayimg on my machine and added the support for it, I've been using this locally for a while now and I didn't have any issue.

I have created a PR here: https://github.com/artemsen/swayimg/pull/195

Let me know please if this is something you would like to add to this tool

**Comment by artemsen** [comment]
Fixed in 386620743996fc3ed0c6756f8ff403598cb5c71a
