### ISSUE TITLE
+ and = does not increase size (swayimg 1.2-1 from AUR)

### ISSUE THREAD

**Issue by EinarMostad** [artemsen/swayimg#2]
I recently installed swayimg and like it a lot. Thank you for making it! :-)
The issue I have is that + and = does not make the picture bigger on my screen. 0 gives me 100% and - gives me a smaller picture. + also makes the picture smaller. = does the same as 0.

Maybe this has to do with the fact that I am using the Norwegian keyboard layout (no)? On my keyboard = is on the same key as 0, but with shift. + is on the key next to it, two keys left of backspace. I think this is where - is on the US layout. - is next to my right shift-key. Maybe there is some mistake in how keypresses are interpreted that does not take into consideration which keyboard layout is used?

**Comment by EinarMostad** [comment]
I should probably add that I use Arch and installed swayimg from the AUR. (https://aur.archlinux.org/packages/swayimg/)

**Comment by artemsen** [comment]
Yeah, I was too lazy to implement full keyboard support =)
Will be fixed in next release.

**Comment by EinarMostad** [comment]
Thank you! :-)
