### ISSUE TITLE
How to get full path of the image

### ISSUE THREAD

**Issue by 3333juul** [artemsen/swayimg#204]
when i use `exec notify-send %` as a binding, it only prints the name of the file, not the full path

**Comment by artemsen** [comment]
`%` is not a full path, but the path you specify when run `swayimg`, so:
`swayimg /full/path/to/image` -> `%` is `/full/path/to/image`
`swayimg realtive/path/to/image` -> `%` is `relative/path/to/image`
`swayimg image` -> `%` is `image`

**Comment by artemsen** [comment]
You can use
```
swayimg ~/Pictures/Backgrounds
```

**Comment by artemsen** [comment]
Just create a simple script `swayimg_pwd`:
```
#!/bin/sh
swayimg --gallery "$(pwd)"
```
and modify the yazi config
```
run = "shell --confirm swayimg_pwd";
```
