### ISSUE TITLE
Add a command for changing the `scale`

### ISSUE THREAD

**Issue by litoj** [artemsen/swayimg#205]
Currently, you can change the scale only for the current image using `zoom <scale mode>`. I would really like to be able to set the scaling mode for all images, like it is being set when starting the program -> `scale <scale mode>`. Perhaps even cycle through the modes like with `mode` or `antialiasing`.

I would use `scale real` often to compare the sharpness of two similar images (as I do now on _imv_).

Thank you for this great application!

**Comment by artemsen** [comment]
Sorry, I don't fully understand what you need.
Is it something like "lets lock scale for the current instance of swayimg"?
You can do it from the command line: `swayimg -c viewer.scale=real`, this will overwrite settings from the config file.

**Comment by litoj** [comment]
1018ee3 does the job, but now you'd have to zoom back every time you zoom just on one image. Both `zoom` and `scale` have their purpose and I don't think they can be interchanged. Also now the behaviour is somewhat counterintuitive to the command name. I can try and submit a pr.

**Comment by artemsen** [comment]
> I can try and submit a pr.

Yeah, it would be nice. English is not my native language, so may be I don't understand what you want.

**Comment by litoj** [comment]
It is not my native language either. Unfortunately neither is C, but it was a change simple enough for me to figure out.
