### ISSUE TITLE
feat: display only files given on the cli if there are multiple

### ISSUE THREAD

**Issue by litoj** [artemsen/swayimg#206]
I would like to be able to view just the images I specified on the commandline to be able to quickly switch between them. Currently, the app views all images in the folder starting with the first argument and the rest is ignored. Instead, if there are multiple image files given, it could display just those, ignoring the contents of the directory.

**Comment by artemsen** [comment]
You can opens only the specified files by setting the [all](https://github.com/artemsen/swayimg/blob/41f63eabffe1669226c93ec5cb1835b862dc0633/extra/swayimgrc#L89) option to `no`.

**Comment by litoj** [comment]
You're right! though I need to use a wrapper, but that's not an issue for my setup, thank you.
```bash
if (($# > 1)); then
  swayimg -c list.all=no "$@"
else
  swayimg "$@"
fi
```
