### ISSUE TITLE
Implement random jump command

### ISSUE THREAD

**Issue by mallniya** [artemsen/swayimg#211]
Random jump is pretty simple and quite useful navigation command, widely used in other image/video viewers

**Comment by artemsen** [comment]
You can start the program with the option `--order=random`.
Or even set the random order permanently in the [config file](https://github.com/artemsen/swayimg/blob/0428aefe21f5f448dfff2e7b257438d517c65a8c/extra/swayimgrc#L83).

**Comment by mallniya** [comment]
Starting program with an option or configuration and have ability to random jump at any given time is 2 separate use cases, so please consider this as a navigation feature not related to viewing mode

**Comment by mallniya** [comment]
Thank you very much :thumbsup: will try to replace feh with swayimg on next update
