### ISSUE TITLE
Set cursor shape in when focused

### ISSUE THREAD

**Issue by diniamo** [artemsen/swayimg#212]
Not sure if this is swayimg's fault, but when switch I from hovering text in another app to swayimg, the blinker cursor shape is retained. Would it be possible for swayimg to set a custom shape (eg. the default or the dragging one)?

**Comment by artemsen** [comment]
Yes, Swayimg still doesn't support cursor shape control.

**Comment by diniamo** [comment]
@artemsen that doesn't seem to work properly, I always get the dragging shape, even if I'm not dragging.

**Comment by artemsen** [comment]
Oh, I forgot about that.
Ok, I will set static shape, at least it doesn't inherit previous state from closest window.
