### ISSUE TITLE
Option to display in new window

### ISSUE THREAD

**Issue by stargazer1984** [artemsen/swayimg#213]
Swayimg looks like an awesome project which supports more image formats then any other wayland image viewer I know but I am missing any option to make it behave like other image viewers in that it opens images in a new window.
Other applications like imv open the image in a new window, allowing easy viewing in terminal based file managers.
However I have not yet found any way to do this with swayimg and I would expect that I am not the only one to miss this behavior.

Is there any way to have swayimg open an image in a new window to work exactly like imv/feh and most other image viewers?

**Comment by stargazer1984** [comment]
That works exactly like I want it to.
But why do I need the mask the sway socket to have swayimg behave like the default windows in sway? Or in other words why does swayimg default to floating mode when I have no such config in my sway config?

**Comment by artemsen** [comment]
It is the Sway integration mode: swayimg creates an "overlay" above the currently active window, which gives the illusion that you are opening the image directly in a terminal window. This is useful if you don't want to break the workspace layout.

**Comment by artemsen** [comment]
There was an option to disable integration with Sway WM, but it was removed some time ago, since the same can be done by unsetting an environment variable [described in the man](https://github.com/artemsen/swayimg/blob/0428aefe21f5f448dfff2e7b257438d517c65a8c/extra/swayimg.1#L97).
