### ISSUE TITLE
Cycle only through files given on cmdline

### ISSUE THREAD

**Issue by omgold** [artemsen/swayimg#214]
When I use the next_file/prev_file operations in viewer mode, it cycles through all files in all directories which contain one of the files specified on the command line.

Not sure if that is a feature or a bug, but in any case I would prefer it to cycle only through the files specified (if not specified a directory explicitly).

In case the current behavior is intended I would like to make a feature request for a switch to change that.

**Comment by artemsen** [comment]
You can disable this in the [config file](https://github.com/artemsen/swayimg/blob/6b9f0cb25f5b78805fcbc568926a191db97f1649/extra/swayimgrc#L89).

**Comment by omgold** [comment]
Ah.

```
[list]
all = no
```

Sorry, overlooked that. Thanks.
