### ISSUE TITLE
About marking files

### ISSUE THREAD

**Issue by alttabber** [artemsen/swayimg#218]
Some image viewers support marking: select some images, and their path is sent to stdout when the program is closed.

Swayimg was one of those, until the feature in version 1.8, until it was silently remove in 1.11.

Why was it removed? Any chance of ever getting it back?

**Comment by artemsen** [comment]
The implementation of this feature was not done in the best way and interfered with the further development of the project. Sorry, I don't remember all the details =)

You can use the `exec` action to print the path to standard output or pass it to some script.
Add to the config file a new binding:
```
[keys.viewer]
Shift+p = exec echo "%"
Ctrl+p = exec myscript.sh "%"
```
