### ISSUE TITLE
Question about "libinotify" dependency

### ISSUE THREAD

**Issue by charbelnicolas** [artemsen/swayimg#224]
When swayimg was building today I noticed the following dependency `libinotify`

`Run-time dependency libinotify found: NO (tried pkgconfig and cmake)`

Isn't that supposed to be `libnotify`? Or am I mistaking it for something else?

**Comment by charbelnicolas** [comment]
![ss_2024_11_27_10_20_03](https://github.com/user-attachments/assets/b4a318b7-b32f-4857-a425-f2f6a4776ea2)

**Comment by artemsen** [comment]
These are the build dependencies for [FreeBSD build](https://github.com/artemsen/swayimg/blob/d67e9ead570c33fa9cca095bb03bde8fcc45400e/meson.build#L75).
`sys/inotify.h` is enough for in Linux.

**Comment by charbelnicolas** [comment]
Cool, good to know, thanks.
