### ISSUE TITLE
Floating window not working

### ISSUE THREAD

**Issue by hajosattila** [artemsen/swayimg#25]
For some reason, it does not open the images as a floating window.

**swayimg**

![scrn-2022-03-03-11-29-04](https://user-images.githubusercontent.com/1567493/156551401-659581cd-323e-4b31-9e58-5c79f2df435e.png)

**imv**

![scrn-2022-03-03-11-29-47](https://user-images.githubusercontent.com/1567493/156551406-bb7fb5bb-17c4-4d4a-8a1e-e9f081004738.png)

Sway Version: 1.7.0 (Arch)

Sorry for my bad English!

**Comment by artemsen** [comment]
> I'm confused that it doesn't put the window in the middle of the screen.

It is the main feature of Swayimg for me. 
So, it works as designed =)

> Then the only question is how I can get it to have a floating window like IMV.

You can use `-g` to define own window geometry, for example:
```
$ swayimg -g 100,100,800,600 photo.jpg
```

**Comment by hajosattila** [comment]
This is a very good solution to my problem! (btw RTFM :grrrr)
I just need to find the perfect center X Y coordinates...
