### ISSUE TITLE
Feature request: Thumbnails (gallery) mode

### ISSUE THREAD

**Issue by timsofteng** [artemsen/swayimg#27]
Hello. Is it possible to add `thumbnails mode` for swayimg?
Something like this:
![image](https://user-images.githubusercontent.com/51912173/159926490-86f6dbd7-24c5-41b1-a149-f90eedc861f9.png)

**Comment by artemsen** [comment]
I'm sure there are specialized applications that can help you manage your image galleries.
This project (I mean Swayimg) is a simple image viewer only.
Sorry, I don't plan to implement this feature.

**Comment by Zeioth** [comment]
Hey I just wanted to say that [xnview](https://www.xnview.com/en/apps/) does exactly that and it's probably what you are looking for. The cool thing about swayimg is the low memory footprint and responsiveness.

**Comment by apprehensions** [comment]
> I'm sure there are specialized applications that can help you manage your image galleries.

Been looking for this, can't find anything. Also XnView is propietary.

**Comment by artemsen** [comment]
Yes, I already thought about this too.
Such feature requires a redesign of the app architecture, so implementing may take a long time.
But I have a couple of ideas =)

**Comment by apprehensions** [comment]
Yay!!
