### ISSUE TITLE
BUG: Segmentation fault when trying to open an incompatible file

### ISSUE THREAD

**Issue by Zeioth** [artemsen/swayimg#31]
Let's say I run 

    swayimg ./*

Because I want to be able to go though all my photos. If there's any incompatible file format in that directory, it will produce a core dump when trying to read it.

Solution: Allow to read only compatible file formats.

**Comment by artemsen** [comment]
Which version do use?
I think it was fixed in 98dfcbacc856510fbd41cbd5a031abc2aa92d5ab.

P.S. You don't need to use `./*` in your scenario. If input files are not specified, swayimg will show all images from the current directory.

**Comment by Zeioth** [comment]
That's great @artemsen !!

It would be great to be able to do the same thing, not only from terminal, but also from a file explorer. EXAMPLE: I open one specific file, but I can also navigate to the next one in the same directory by pressing AvPag/RePag.

Opening a file in 
![screenshot_2022-07-27_17-00-21_567674403](https://user-images.githubusercontent.com/3357792/181281039-e907e94d-8054-469f-a5b1-cd6e11e747f2.png)

**Comment by artemsen** [comment]
Ok, I will think about the navigation feature =)

**Comment by artemsen** [comment]
> It would be great to be able to do the same thing, not only from terminal, but also from a file explorer.

[Supported](https://github.com/artemsen/swayimg/commit/11e65c0992974e979d16c93736f0175c04204d38) for now, just add option `--all`
