### ISSUE TITLE
Fullscreen fails to load as default

### ISSUE THREAD

**Issue by Pound-Hash** [artemsen/swayimg#38]
In my config I have,
```
fullscreen = yes
font = JetBrainsMonoNL Nerd Font Mono
font-size = 17
font-color = #cccccc
app_id = swayimg
sway = no

# Background for transparent images (none, grid, or RGB, e.g. #112233)
background = grid

# Window background mode/color (none or RGB, e.g. #112233)
window = #000000

# Always open all files in the same directory
all = no
```
But running `swayimg` displays a window first, and I can enter fullscreen afterward by pressing `f`.

The other settings load correctly.

**Arch**
**swayimg** 1.8
**foot terminal** 1.12.1
**river compositor** 0.1.3

**Comment by artemsen** [comment]
It appears to be the compositor related issue, I can't reproduce the error with sway/wlroots.

**Comment by willemw12** [comment]
Same distro. No swayimg config file. No reference to swayimg in the sway config file.

For me in 1.8, `swayimg --fullscreen FILE` (and `swayimg --fullscreen --scale=fit FILE`) prints:

    Incompatible arguments: sway rules can not be used in full screen mode

Swayimg starts in fullscreen mode.

But I see another issue, which may be related:

the image is not stretched to fit the screen anymore when running `swayimg --fullscreen --scale=fit FILE`.

Also the --scale section in man page seems out-of-date (optimal and real were added, default was removed).

**Comment by artemsen** [comment]
> Incompatible arguments: sway rules can not be used in full screen mode

I'll remove this annoying message, thanks.

> But I see another issue, which may be related

This is #42, I've already fixed it.

> Also the --scale section in man page seems out-of-date

Yeah, documentation is the hardest part of the project :) I will fix it, think you!

**Comment by artemsen** [comment]
@Pound-Hash, could you check version 2.0?
Is the problem still relevant?

**Comment by Pound-Hash** [comment]
> @Pound-Hash, could you check version 2.0? Is the problem still relevant?

I'm on a new system now, Gentoo w/ sway. This issue doesn't occur under swayimg 1.12.

**Comment by artemsen** [comment]
Thank you!
