### ISSUE TITLE
[feature] anti aliasing

### ISSUE THREAD

**Issue by bgkillas** [artemsen/swayimg#49]
things get quite blocky when not on real scaling i think anti aliasing would fix this right?

**Comment by artemsen** [comment]
Yeah, currently there is a very stupid scaling algorithm without any antialiasing. I'll add this feature in next release.

**Comment by slashdevslashurandom** [comment]
Seems to me like the anti-aliasing algorithm currently just blurs the image a bit before scaling it, not resolving the "blockiness" issue at all.

Here is an example, a screenshot from "Contra" displayed zoomed-in using swayimg with anti-aliasing on.

![image](https://github.com/artemsen/swayimg/assets/53902042/349a0808-357c-440a-ac8a-a4312503ddab)

And here is the same image, upscaled to the same size using GIMP using "cubic" filtering.

![image](https://github.com/artemsen/swayimg/assets/53902042/f9887832-a6cb-412e-a283-2736ab175b67)

While the image upscaled in GIMP is blurry as the result of scaling, no detail is lost. You can still see that the medal representing the character's one remaining life has a blue circle in the center. This detail is lost on the image upscaled by swayimg. In addition, swayimg's upscaling is still just as blocky.

**Comment by artemsen** [comment]
Yes, you are right, there is a simple blur instead of real anti-aliasing.
