### ISSUE TITLE
Hook on image render finishing

### ISSUE THREAD

**Issue by timsofteng** [artemsen/swayimg#53]
Hello. I'm trying to build lightweight screenshot tool using swayimg as image viewer. The main reason why I do it is focus troubles using only grim + slurp. 
If I open some selector on the website which required focus and then press grim + slurp the selectors closes because of focus loosing.
So I've added `swayimg` to the chain.
But the problem is I cannot decide when to run `slurp` to grab the part of my screen because of some normal delay to render image on the screen...
It would be cool to have hook or something like this when image is rendered successfully to run next command.

Here is my script with weird sleeping which I would like to drop:
```
#!/bin/sh

grim -| swayimg -f - &
sleep 0.2

grim -g "$(slurp ; pkill -9 -n swayimg)" -  | swappy -f - 
```

**Comment by artemsen** [comment]
Hmmm... Which type of hook it should be? Execute external command?
Another problem is that `swayimg` doesn't know that image buffer was completely displayed, it just fill the buffer and pass it to to the display server via wayland protocol.

**Comment by timsofteng** [comment]
> Hmmm... Which type of hook it should be? Execute external command? Another problem is that `swayimg` doesn't know that image buffer was completely displayed, it just fill the buffer and pass it to to the display server via wayland protocol.

I just cannot get the right way to invoke slurp in my script... I thought it is good idea to have the hook when image will be displayed on screen. If I'm going on wrong way I would happy to hear any recommendation how to achieve my goal.
Thanks

**Comment by artemsen** [comment]
`swayimg` doesn't create a window until it loads the first image.
May be instead of `sleep` you can ask window manager whether swayimg's window is displayed.
Something like this: `swaymsg -t get_tree | grep swayimg`

**Comment by artemsen** [comment]
You can replace sleep with
```
until swaymsg -t get_tree | grep -q '"app_id": "swayimg'; do sleep 0.01; done
```
But there is another `sleep` =)

**Comment by timsofteng** [comment]
@artemsen What if I have another one swayimg instance opened?

**Comment by artemsen** [comment]
You can set different appid for different instances with `--class` option and then grep it:
```
grim -| swayimg -f -c myid123 - &
... grep -q '"app_id": "myid123' ...
```

**Comment by timsofteng** [comment]
Thanks you very much!
Closed.

**Comment by artemsen** [comment]
You're welcome! =)
