### ISSUE TITLE
Cannot open svg

### ISSUE THREAD

**Issue by timsofteng** [artemsen/swayimg#54]
```
> swayimg Re-send.svg
Re-send.svg: unsupported format
```
Alpine Edge

**Comment by artemsen** [comment]
It's because Alpine has [disabled](https://build.alpinelinux.org/buildlogs/build-edge-x86_64/community/swayimg/swayimg-1.9-r0.log) SVG support in `swayimg`:
```
Dependency librsvg-2.0 skipped: feature svg disabled
```
I don't know why, sorry.

**Comment by timsofteng** [comment]
Thanks. Got it. I'll try to figure out.

**Comment by Ikke** [comment]
For the record, the `swayimg-full` subpackage contains a build with all optional features enabled

> Run-time dependency librsvg-2.0 found: YES 2.54.4
