### ISSUE TITLE
geometry option y-offset

### ISSUE THREAD

**Issue by marcusatiliusregulus** [artemsen/swayimg#57]
# expected behaviour
hi, i want to open an image exactly where my current window is, covering it (without the titlebar).
# actual behaviour
however it gets placed about 30 (pixel?, without the window decoration) lower than it should; am i doing something wrong?

# Steps to reproduce
requires jq, imagemagick, slurp
```fish
#!/usr/bin/env fish
# get current window's location
function getwin
        # MAYBE IM DOING SOMETHING WRONG HERE??
        swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y),\(.width),\(.height)"'
    end
getwin # output: 477,265,966,580
# create sample image of this exact size with imagemagick
convert -size 966x580 canvas:red red.png
# and this should cover the window. i tried different scale options, which didnt make a difference
swayimg --geometry=(getwin) --window="#000000" red.png
# but the image is displayed too low, you can measure the exact values with slurp:
slurp -f "%x,%y,%w,%h"
```
# etc
later i want to use it to overlay images for previewing them in a terminal file explorer, i would probably calculate the position then by dividing the window width by $COLUMNS to get the width of a terminal cell

swayimg version 1.9
sway version 1.7
arch linux 6.0.6-arch1-1

**Comment by artemsen** [comment]
Hi,
As far as I remember, the `rect` node contains coordinates of the window without its decoration. May be you need to read or calculate height of the window title bar.
Also, the `jq` query in your sample shows coordinates of all visible windows. Try `select(.focused?)`.

**Comment by marcusatiliusregulus** [comment]
ok, i've checked again, but the decoration is definitely not the problem; the y value is off by 30. can you reproduce it?

> Try `select(.focused?)`.
ok

**Comment by marcusatiliusregulus** [comment]
Found the problem: swayimg seems to add the height of the statusbar (i just use the regular `bar {...}` command) to the y value... if i disable the statusbar or move it from top to bottom everything works as expected...

**Comment by artemsen** [comment]
Yes, you are right. Swayimg [shifts](https://github.com/artemsen/swayimg/blob/2d8fe40136af9776f86123a81c7fd3f852601387/src/sway.c#L327) coordinates because it lives inside the Sway coordinate system. Works as designed =)
