### ISSUE TITLE
Feature request: absolute positioning

### ISSUE THREAD

**Issue by marcusatiliusregulus** [artemsen/swayimg#58]
As discussed in #57 the `--geometry` option is relative to the current node and thus the easily obtainable absolute position of a window is not useful as a value for this option. While the relative position is computable it would be of great help if there was another option to just pass the absolute value to.

Kind regards, love the project

**Comment by artemsen** [comment]
Swayimg splits the `--geometry` option into two parts: top-left corner position and window size. Position is passed directly to the Sway WM without any shifts. Size is passed to the Wayland compositor (also without any changes). Status bar window is not a "Sway window", so it has negative position form the Sway perspective.
I wouldn't want to change this behavior by adding a coordinate converter.

And there are no "absolute coordinates", virtual only =) 
For example, I have multiple displays with different HiDPI settings (scale factors). One of my display has 4K resolution, but there are only 2500 "virtual" pixels by horizontal. I should use these virtual coordinates to said Sway where the window should be placed. And the "virtual" width I have to pass to the Wayland compositor. There is no absolute values in that chain.

But I will add the ability to specify negative coordinates if it helps you.

**Comment by marcusatiliusregulus** [comment]
sadly this (6f2ea) doesn't help me. however, since you use the sway `move position` command to position the window, couldnt you use `move absolute position` instead if the user indicates he wants that? you wouldn't have to convert anything and if it's a new option you wouldnt even have to change the current behaviour...

**Comment by artemsen** [comment]
Now `--geometry` uses absolute coordinates and size.
I hope this helps =)

**Comment by marcusatiliusregulus** [comment]
Yes, this is exactly what i imagined! thanks so much 🎉
