### ISSUE TITLE
Do I need sway window manager/compositer to use swayimg?

### ISSUE THREAD

**Issue by jiang-qian** [artemsen/swayimg#60]
I'm on stock Debian 11, Gnome 3 desktop environment. Feh doesn't support multiple monitor under wayland. So build swayimg from source but when running it I get 
SWAYSOCK variable is not defined
wl_registry@2: error 0: invalid version for global wl_output (4): have 2, wanted 3
Does swayimg not run under stock gnome3? If so, what are my options for viewing images under gnome3/wayland that respect multiple monitor (i.e. I want the image displayed in full screen mode on a particularly monitor?)

**Comment by artemsen** [comment]
You only need Sway if you want to control the size or position of the window.
The error "invalid version for global wl_output" refers to Wayland, you have an old version (2) of the wl_output protocol, and Swayimg needs the 3rd one.
I am not sure, but try to update your system (`sudo apt-get update && sudo apt-get upgrade`).

**Comment by jiang-qian** [comment]
Unfortunately my system is up to date. I prefer debian stable, so I'll wait for another half year till version 12 comes out and upgrade to that. 

All I want is an image viewer that allow me to specify, in wayland, to show an image, in full screen, on a particular monitor in a multi-monitor set up, like what I did with feh back in the days. Would swayimg be able to do that without sway?

If not swayimg, are you away of any image viewer that allow me to specify monitor to display under wayland? Thanks for your help!

**Comment by artemsen** [comment]
> Would swayimg be able to do that without sway?

No. It is possible to open an image in full screen, but you can not control the position of the window, even specify the monitor.
Positioning is the task of the window manager, not Wayland. Swayimg only supports Sway WM.

> If not swayimg, are you away of any image viewer that allow me to specify monitor to display under wayland?

Try [imv](https://sr.ht/~exec64/imv/).

**Comment by jiang-qian** [comment]
Thanks I tried that but it doesn't allow me to specify which monitor to
display the image.
