### ISSUE TITLE
Corrupted output of some AVIF images

### ISSUE THREAD

**Issue by ndren** [artemsen/swayimg#61]
Some AVIF images appear corrupted (stretched diagonally). I have some test cases.

The source image, [arch.png](https://user-images.githubusercontent.com/59375667/215263525-134b749b-3cdd-476c-97b3-dd4a186d97b9.png), has been converted to [imagemagick.avif](https://s1.fileditch.ch/nvrfzQnfNSUXXjXOFoHo.avif) with `magick convert arch.png imagemagick.avif` and to [ffmpeg.avif](https://s1.fileditch.ch/nvrfzQnfNSUXXjXOFoHo.avif) with `ffmpeg -i arch.png ffmpeg.avif`

Both these AVIF images [display this in swayimg](https://user-images.githubusercontent.com/59375667/215263763-ff3959ee-38ed-4f82-bf3b-cdc817bdbec7.png), which is not something I can reproduce when using any other image viewer with the same images.

This is not reproducible with other AVIF images, like [this one](https://s1.fileditch.ch/WrgyoANHNNbfTXtbbGd.avif), so it might be the specific AVIF encoding?

**Comment by artemsen** [comment]
Fixed, thank you!
