### ISSUE TITLE
Alias < and > for p and n

### ISSUE THREAD

**Issue by ndren** [artemsen/swayimg#68]
I'm used to using < and > to go to the previous and next file since those are the defaults in mpv. Could those be added as aliases as well?

I know there are already a few aliases, but I keep pressing the wrong key, so please consider it! Thank you.

**Comment by artemsen** [comment]
Hi!
You can create own key bindings in the config file (`~/.config/swayimg/config`).
Just add the following lines:
```
[keys]
less = prev_file
greater = next_file
```
But you need to build Swayimg from the master branch, this feature is not released yet.
