### ISSUE TITLE
[Bug] in swayimg-git v1.10.12-1 - wl_shm@4: error 1: invalid size (0)

### ISSUE THREAD

**Issue by Zeioth** [artemsen/swayimg#69]
I just reinstalled from swayimg-git and by running:

    swayimg ./images/1.png 

I get the output 

    wl_shm@4: error 1: invalid size (0)

And the image does not open.

**OS**: Arch linux + sway
**Config file**: none, using defaults

**Comment by Zeioth** [comment]
I've tried with more images, same result.

**Comment by Zeioth** [comment]
Also, swayimg keeps running on background using 100% CPU.

**Comment by bgkillas** [comment]
i can replicate this bug however it only happens after i move the window via super+click drag
also moving it to another window seems to crash with Floating point exception (core dumped) so thats neat

**Comment by artemsen** [comment]
I reproduced the problem by moving the window to another display. Bug =)

**Comment by artemsen** [comment]
Guys, could you check with the latest master?

**Comment by Zeioth** [comment]
I just tested, I can confirm its been fixed.

**Comment by bgkillas** [comment]
seems to work fine now

**Comment by artemsen** [comment]
Thank you!!
