### ISSUE TITLE
Weird compression checkerboard artifacts with a certain grey color

### ISSUE THREAD

**Issue by raiguard** [artemsen/swayimg#78]
I use `swayimg` as a way to "freeze my screen" when taking screenshots with grimshot. It works pretty well, but I noticed that there is a weird "checkerboard" artifact pattern on a certain grey color that is present in most of my screenshots.

Have a look here:
![image](https://user-images.githubusercontent.com/3515394/236643768-598aa4ac-0dc5-43f0-997e-45d86979e79e.png)

The background of the main interface has a noticeable checkerboard. Now, the same screenshot, but cropped with gimp:

![image](https://user-images.githubusercontent.com/3515394/236643789-868fc746-a217-48f2-9f66-6dcdb8fc10cf.png)

You can see that the checkerboard is not present.

**Comment by artemsen** [comment]
Looks like the source image ("freeze my screen") has an alpha channel.
I don't know how this "freeze" works, but as workaround I would suggest to use `--background=0` argument to remove the checkerboard.

**Comment by raiguard** [comment]
Ah, there it is, setting that flag fixes it. Thank you very much!

Here is the "frozen screenshot" script. It's pretty simple, but it works!
```sh
#!/bin/sh

grim -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name') /tmp/freeze-screenshot
swayimg -f /tmp/freeze-screenshot -b none &
grimshot --notify "$1" area
killall swayimg # We are only using swayimg for this purpose
```

![image](https://user-images.githubusercontent.com/3515394/236662255-dc563ff6-9083-469e-bf88-510fdf57644a.png)
