### ISSUE TITLE
Add option to change step for `step_up/down/left/right` and `zoom_in/out`

### ISSUE THREAD

**Issue by dmyTRUEk** [artemsen/swayimg#81]
I think it would be very convenient to have option to change step independently for any "sized" bind. Here is how I see it could work:

This uses default step:
```
Up = step_up
Down = step_down
Left = step_left
Right = step_right
```

This uses non-default step:
```
Up = step_up 10
Down = step_down 10
Left = step_left 10
Right = step_right 10
```

The question is what exactly `10` should mean? I thought of this ideas:
- If number is integer (no decimal point) then it's in pixels
- If number is float (with decimal point) then it's in "default steps", so that `2.0` means the step is twice as big as default, and `0.5` means that the step is half of the default step.

Also, mentioned ideas can be combined, and both be implemented.

And now to the last part, zoom:

This uses default step:
```
<some button> = zoom_in
<some button> = zoom_out
```

This uses non-default step:
```
<some button> = zoom_in 2.0
<some button> = zoom_out 2.0
```

Here raises the same question as for step: what this number should mean? In case of zoom i can't think of anything else than multiples of default zoom, so that `2.0` means that zoom step is twice bigger than default, `0.5` means that zoom step is twice less than default.

If you have any other ideas, i would love to hear them.

**Comment by artemsen** [comment]
First of all, these steps are definitely not key binding settings.
These steps currently depend on the [window size](https://github.com/artemsen/swayimg/blob/f93289bf94fec5bcaa397662ae7665d435798a54/src/canvas.c#L358) and [image scale](https://github.com/artemsen/swayimg/blob/f93289bf94fec5bcaa397662ae7665d435798a54/src/canvas.c#L408).
We can create standalone move/zoom settings and replace the constant `10` with them, but I'm not sure if we really need that.

**Comment by dmyTRUEk** [comment]
I thought of this exactly in keybinds section, because i think it could be useful to make different keybinds for moving with different precision, for example something like this:
```
h = step_left 100
j = step_down 100
k = step_up 100
l = step_right 100
H = step_left 10
J = step_down 10
K = step_up 10
L = step_right 10
```

**Comment by artemsen** [comment]
It will take a lot of rework to mix key bindings with custom parameters.
To be honest, I don't like this idea - it's too complex for such small feature.
