### ISSUE TITLE
Add option to control `zoom_reset`

### ISSUE THREAD

**Issue by dmyTRUEk** [artemsen/swayimg#82]
Here is how I see it could be done:

Default `zoom_reset` (works same as now - resets to default)
```
<some button> = zoom_reset
```

Reset to optimal:
```
<some button> = zoom_reset optimal
```

Reset to fit:
```
<some button> = zoom_reset fit
```

Reset to real:
```
<some button> = zoom_reset real
```

Also, maybe this shouldn't be a `zoom_reset`'s option, maybe this should be separate command, something like `zoom_set`?

**Comment by artemsen** [comment]
We already have `zoom_real` (100%) and `zoom_reset` which set a predefined scale depending on the configuration.
I don't think we need to duplicate these settings.

**Comment by dmyTRUEk** [comment]
But if somebody would want to bind each type of zoom reset (optimal, fit and real) to separate keys, then currently it's impossible.

Maybe the solution is to keep `zoom_reset` (which resets to default in config) and `zoom_real` (which resets to 100%), but also add `zoom_optimal` and `zoom_fit`?
