### ISSUE TITLE
Set background color for in-window overlap

### ISSUE THREAD

**Issue by carlsmedstad** [artemsen/swayimg#87]
Hey :wave:

I'm in the process migrating to swayimg from imv and I have a question / feature request. While I really like the feature of opening images in floating windows above the terminal, sometimes I want a dedicated non-floating window to view images. When de-floating the swayimg window the overlap is currently transparent, i.e. I see my background image:

![20230722_07h26m32s_grim](https://github.com/artemsen/swayimg/assets/6952324/8c9ec9a0-2aaf-41a8-a389-c54ef990d91e)

Is there a way, either in sway or in swayimg, to set a default background color for in-window overlap so that I don't see my background image in the swayimg window?

Much appreciated, thanks!

**Comment by artemsen** [comment]
Hi!
Yes, you can use `background` and/or `window` arguments to replace transparency with a solid color::
```
$ swayimg --help | grep background
  -b, --background=XXXXXX  set image background color: none/[grid]/RGB
  -w, --window=XXXXXX      set window background color: [none]/RGB

$ swayimg -b 0 -w 0x00ff00 image.png
```
Argument `-n, --no-sway` disables integration with Sway, so you will get a non-floating window.

Also, it's possible to save these parameters permanently in the [config file](https://github.com/artemsen/swayimg/blob/b5758c486cd12ddfa408da04ce23e1d417ed149c/extra/swayimgrc#L17).

**Comment by carlsmedstad** [comment]
Ah, I missed that option looking through the documentation, works like a charm! Thank you for the quick reply  :)
