### ISSUE TITLE
slideshow timer reset on "next image"

### ISSUE THREAD

**Issue by verygitmuchhub** [artemsen/swayimg#93]
Hey guys,

when running a `-l` (`--slideshow`) with e.g. a 4 second timer, pressing space (next image) after 3 seconds will show the next image for 1 second only. 

I'd say there should be a timer reset when swayimg shows the next image.

**Comment by Rentib** [comment]
@artemsen wouldn't it be enough to add
`    slideshow_ctl(ctx, ui, ctx->slideshow);`
after line 230 in viewer.c?

I quickly checked it and it seems ok

**Comment by artemsen** [comment]
Merged to master.
@Rentib thank you!

**Comment by borkedporcupine** [comment]
@artemsen How do I set a timer for the slideshow mode?  It doesn't seem to accept any syntax I provide.

**Comment by borkedporcupine** [comment]
> [@artemsen](https://github.com/artemsen) How do I set a timer for the slideshow mode? It doesn't seem to accept any syntax I provide.

I see this need to be set in the config file but I don't seem to be able to get swayimg to read that config. I've set environmental variables, moved the file all around it just doesn't read it.
