### ISSUE TITLE
APNG file format support

### ISSUE THREAD

**Issue by ludg1e** [artemsen/swayimg#95]
APNG (animated png) is a [widely supported](https://caniuse.com/apng) format in the web, though not so popular as GIF

Would be nice to see it supported in swayimg
Ways of supporting it:
- patch libpng (https://sourceforge.net/projects/libpng-apng/) *actively maintained* or https://sourceforge.net/projects/apng/
- any other idea?

Related info:
libpng issue: https://github.com/glennrp/libpng/issues/267
PNG spec 3rd edition with APNG support: https://w3c.github.io/PNG-spec/#apng-frame-based-animation

Thank you

**Comment by artemsen** [comment]
Sorry, I don't plan to distribute the patched libpng.

**Comment by ludg1e** [comment]
Ok, thank you.
Closing as I can already understand that it won't be added.
