### ISSUE TITLE
PSD read image format support

### ISSUE THREAD

**Issue by ludg1e** [artemsen/swayimg#98]
*copy-paste of my other issue as i'm too lazy*

Would be nice to see the feature of reading and viewing PSD files

Ways of supporting it:
- use libpsd (https://github.com/TheNicker/libpsd)

Thank you

**Comment by artemsen** [comment]
As I can see, there is no one OS that has libpsd in its repository.

**Comment by andis-sprinkis** [comment]
@artemsen looks like ffmpeg can get the preview image out of a PSD file

```sh
ffmpeg -v error -y -i "test.psd" -frames:v 1 -vf "scale='if(gt(iw,ih),min(500,iw),-1)':'if(gt(ih,iw),min(500,ih),-1)':flags=lanczos" "test.png"
```

from [psd-thumbnails-linux/psd-thumbnailer at main · hutber/psd-thumbnails-linux](https://github.com/hutber/psd-thumbnails-linux/blob/main/psd-thumbnailer)
